### ISSUE TITLE
Is it possible to directly manipulate Excel and invoke the local printer to print an XLSX file?

### ISSUE THREAD

**Issue by whqgo** [zitsen/ooxml-rs#13]
Can we achieve direct printing of XLSX files, similar to using 'PrintOut' in Python with win32com?

**Comment by zitsen** [comment]
Basically no. Seems that there are a lot of things to do/learn to print.

1. https://users.rust-lang.org/t/any-rust-library-that-helps-with-printers-on-windows/67689/2
2. https://users.rust-lang.org/t/how-to-send-pdf-or-a-document-to-printer/74963
3. https://stackoverflow.com/questions/72073073/how-to-send-pdf-or-a-document-to-printer-in-native-rust

**Comment by whqgo** [comment]
ok
