### ISSUE TITLE
Crash when trying to parse `xlsx` file

### ISSUE THREAD

**Issue by qarmin** [zitsen/ooxml-rs#7]
https://github.com/zitsen/ooxml-rs/blob/e97dc1c475a68c1d9c154b1d448e0d35dc4806fb/src/document/spreadsheet/mod.rs#L123-L124

```
thread '<unnamed>' panicked at 'parse worksheet error: XmlDeError(Custom("missing field `c`"))', /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/ooxml-0.2.5/src/document/spreadsheet/mod.rs:124:18
```
[Arkusz.xlsx](https://github.com/zitsen/ooxml-rs/files/8693599/Arkusz.xlsx)

**Comment by zitsen** [comment]
released v0.2.6
